### ISSUE TITLE
System.Version json serialization/deserialization is not fully compatible between net461 and netcoreapp3.1/net5.0 versions of the library

### ISSUE THREAD

**Issue by alexandru-malaescu** [UiPath/coreipc#54]
`System.Version` JSON serialization/deserialization is not fully compatible between `net461` and `netcoreapp3.1`/`net5.0` versions of the library. 

This seems to be due to `Netwonsoft.Json v12.0.3` dependency, which we are using in our `JsonSerializer`. It uses a different format for JSON serialization/deserialization of `System.Version`, depending on the target framework (net461 vs netcoreapp3.1/net5.0). It also looks like a known issue https://stackoverflow.com/a/60962363. 

Deserialization seems to have been narrowed down in the newer target frameworks, basically dropping support for json serialization format that is generated by the library running on net461.

On `netcoreapp3.1/net5.0`
```
Version(1.2.3.4) -> serialize() -> "\"1.2.3.4\""

"\"1.2.3.4\"" -> deserialize() -> Version(1.2.3.4)
```

On `net461` 

```
Version(1.2.3.4) -> serialize() -> "{\"Major\":1,\"Minor\":2,\"Build\":3,\"Revision\":4,\"MajorRevision\":0,\"MinorRevision\":4}"

"{\"Major\":1,\"Minor\":2,\"Build\":3,\"Revision\":4,\"MajorRevision\":0,\"MinorRevision\":4} -> deserialize() -> Version(1.2.3.4)

"\"1.2.3.4\"" -> deserialize() -> Version(1.2.3.4)
```

**Comment by lbargaoanu** [comment]
You'll just have to workaround it in your own code.
